import { IThemeProps } from "../../assets/types/utils/themes/Theme";

export const ThemeLight = <IThemeProps>{
    primaryColor: "#6e717a",
    primaryBgColor: "#fff",
    primaryBorderColor: "#e9e9e9",
    primarySvgColor: "#62687b",
    secondaryColor: "",
    secondaryBgColor: "#fcfcfc",
    secondaryBorderColor: "",
    secondarySvgColor: "#4d6c95",
    primaryColorHover: "#6585b5",
    primaryBgColorHover: "#6585b530",
    headingColor: "#2b2350",
    headingBgColor: "#fff",
    markColor: "#ee4878",
    markBorderColor: "#ed1d59",
    markBgColor: "#ee487830",
    createColor: "#fff",
    createBorderColor: "#536f99",
    createBgColor: "#6585b5",
    errorColor: "#fff",
    errorBorderColor: "#995353",
    errorBgColor: "#a27575",
    warningColor: "#d1cc31",
    warningBorderColor: "",
    warningBgColor: "#d1cc3130",
    successColor: "#fff",
    successBorderColor: "#53995c",
    successBgColor: "#75a27b",
    informationColor: "#6585b5",
    informationBorderColor: "",
    informationBgColor: "",
    tagColor: "#464a50",
    tagBorderColor: "#000",
    tagBgColor: "#464a5030",
    dateTimeColor: "#464a50",
    paragraphColor: "#b3b7c4",
    surveyBgColor: "#4d7972",
    meetingBgColor: "#794d4d"
}